[font]
size = 12

[env]
WINIT_X11_SCALE_FACTOR = "1"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 1

# [general]
# import = ["dracula.toml"]
